package ru.karelin.tmwebspring.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-03T11:54:19.769+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://soap.tmwebspring.karelin.ru/", name = "LoginEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface LoginEndpoint {

    @WebMethod
    @RequestWrapper(localName = "singIn", targetNamespace = "http://soap.tmwebspring.karelin.ru/", className = "ru.karelin.tmwebspring.soap.SingIn")
    @ResponseWrapper(localName = "singInResponse", targetNamespace = "http://soap.tmwebspring.karelin.ru/", className = "ru.karelin.tmwebspring.soap.SingInResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String singIn(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebMethod
    @RequestWrapper(localName = "singOut", targetNamespace = "http://soap.tmwebspring.karelin.ru/", className = "ru.karelin.tmwebspring.soap.SingOut")
    @ResponseWrapper(localName = "singOutResponse", targetNamespace = "http://soap.tmwebspring.karelin.ru/", className = "ru.karelin.tmwebspring.soap.SingOutResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean singOut();
}
